### ISSUE TITLE
已毕业无法登录？

### ISSUE THREAD

**Issue by YuhZheng** [xmcp/AsHole#6]
可以收到验证码，但是登录的时候总是显示登录失败...很怀念树洞啊 想看看旧贴 以前毕业的学长/学姐还可以毕业后继续在旧洞里一起聊天来着 现在都要失联啦...希望可以修复一下毕业生登录的接口~

**Comment by xmcp** [comment]
咨询了相关人员，不允许非在校生登录树洞是隐私上的考虑。
